### PR TITLE
change obi stop to send SIGTERM, wait, then send SIGKILL

### PR DESCRIPTION
**Pull request by Gobiner**
To my mind, this commit addresses & closes issues #80 and #85. This commit is based on the `better-pkill` branch which is PR #79.

### CODE REVIEW

**Comment by jshrake** [comment]
@Gobiner Can you uncouple this MR from bcbac5e44b7aeea4d6d4a0c0ff32a4544fa9f88d

**Comment by tomjakubowski** [comment]
This is going to add 2 seconds onto every stop + go command for what seems like a marginal benefit to me.

**Comment by tomjakubowski** [comment]
(the possibility that someone else might launch their app in that 2 second window and get killed by the SIGKILL also troubles me)

**Comment by jshrake** [comment]
> This is going to add 2 seconds onto every stop + go command for what seems like a marginal benefit to me.

This is a fair point.

**Comment by Gobiner** [comment]
To my mind, having `obi stop [room]` reliably stop any launched processes is a significant benefit. If JC or Fred do an `obi go dest` and the app gets stuck in an infinite loop such that SIGTERM isn't sufficient (I have personally experienced this), then JC or Fred have little recourse.

**Comment by Gobiner** [comment]
According to the manpages on OSX and 16.04, sleep can take fractional seconds as a parameter. So we could have the interim pause be 0.5 seconds or 1 second or whatever your favorite number is.

**Comment by Gobiner** [comment]
@jshrake I have rebased the commit onto `dev`

**Comment by Gobiner** [comment]
> (the possibility that someone else might launch their app in that 2 second window and get killed by the SIGKILL also troubles me)

I don't see increased danger from this change. Two obi users targeting the same room _must_ manage their own out-of-band mutex if they don't want to step on each others' toes.

**Comment by tomjakubowski** [comment]
>  Two obi users targeting the same room must manage their own out-of-band mutex if they don't want to step on each others' toes.

Previously user A could watch for the app to "die" on the wall before running her own "obi go". Now that is no longer the case; user A has to watch for the app to die, and wait 2 seconds.

**Comment by jshrake** [comment]
@dankegel and @EchoAbstract both suggested in slack that we poll after the soft kill to see if we need to wait and then send a hard kill. Something like:

`so kill gently; while ps | grep -v grep | grep -w foo; do sleep 1; kill harder; done`

I think this is a better approach and resolves the issues @tomjakubowski raised. Thoughts?

**Comment by EchoAbstract** [comment]
@jshrake we may want to try `sleep .5` for the sleep interval

**Comment by dankegel** [comment]
yeah, python's sleep has finer granularity than shell's sleep.  Wouldn't go any lower than 0.5, though.

**Comment by Gobiner** [comment]
The 23c03b0 version implements polling after sending SIGTERM, sending SIGKILL if pgrep still finds processes.

**Comment by Gobiner** [comment]
> Previously user A could watch for the app to "die" on the wall before running her own "obi go". Now that is no longer the case; user A has to watch for the app to die, and wait 2 seconds, to avoid their own launch succumbing to collateral damage.

I've thought about this and I can't convince myself it's true. Assuming both users have the same up-to-date version of obi, if user A starts `obi go room` their instance isn't launched until their own X-second long `obi stop room` finishes.

**Comment by Gobiner** [comment]
Yesterday I had a hung newsdisco that I couldn't stop with `obi stop hex`, and I had to send SIGKILLs to each machine.

**Comment by tomjakubowski** [comment]
You could have just as easily stopped it with "obi stop --signal=SIGKILL"
or whatever. This PR introduces clever, but spooky, sleep action. I think
we should let humans be clever instead of trying to make our tools that
way.

**Comment by jshrake** [comment]
> This PR introduces clever, but spooky, sleep action. I think
we should let humans be clever instead of trying to make our tools that
way.

Despite my original support for the scheme, I agree.

> You could have just as easily stopped it with "obi stop --signal=SIGKILL"
or whatever.

I'm OK with this provided that --signal is optional and by default, you get SIGTERM.

**Pull request closed without merging**
