### PR TITLE
Add Ubuntu upgrade instructions

### LINKED ISSUE #36: README.md is lacking upgrade instructions for Ubuntu
just what the subject reads. Mac has upgrade instructions, but I'm not seeing any for ubuntu.

### PR DESCRIPTION
**Pull request by tomjakubowski**
closes #36

### CODE REVIEW

**Comment by tomjakubowski** [comment]
look good to you, @mattieruth ?

**Comment by mattieruth** [comment]
the instructions didn't work for me but my obi may be so old that it's beyond upgrade and needs a wipe and start over.

**Comment by mattieruth** [comment]
actually i should say that the pip line completed without failure, but after upgrading my greenhouse template and running `obi new greenhouse junk` I got the following:

```
Traceback (most recent call last):
  File "/home/mattieruth/.local/bin/obi", line 9, in <module>
    load_entry_point('oblong-obi==3.0.1', 'console_scripts', 'obi')()
  File "/home/mattieruth/.local/lib/python2.7/site-packages/obi/obi.py", line 140, in main
    g_speak_home = get_g_speak_home(arguments)
  File "/home/mattieruth/.local/lib/python2.7/site-packages/obi/obi.py", line 90, in get_g_speak_home
    g_speak_home = items[-1]
IndexError: list index out of range
```

**Comment by tomjakubowski** [comment]
Ah, looks like a bug in obi… let me see about fixing that.

**Comment by tomjakubowski** [comment]
@mattieruth if you check out this branch: https://github.com/Oblong/obi/pull/40

And then cd into it, run `pip install --user --upgrade .`, and try `obi new greenhouse junk`, do you get a nicer error message? That nasty IndexError looks like it would've happened if `/opt/oblong` existed, but obi couldn't find a directory that looked like a g-speak home in there.

**Comment by mattieruth** [comment]
now i got this pretty message!
```
Could not find the g_speak home directory in /opt/oblong
Run new again and specify: --g_speak_home=/path/to/g-speak
```

nice work.  and now i remember that I loaned my computer out this week to a Dr. Tregre and told him it was fine to wipe away all things in /opt.  oops.  I'd say this looks good to me :-)

**Comment by tomjakubowski** [comment]
sweet!

**Pull request merged**
