### PR TITLE
Shut up cmake, make obi developers more productive

### PR DESCRIPTION
**Pull request by tomjakubowski**

### CODE REVIEW

**Comment by Gobiner** [comment]
Can you rebase this onto `dev` and make the merge target also `dev`?

**Comment by Gobiner** [comment]
Should obi check to see if CMakeLists.txt has been touched after the cmake-success file was created, and re-run cmake if so?

**Comment by tomjakubowski** [comment]
@Gobiner good question, the answer to which is "no". cmake itself will detect changes to CMakeLists.txt and re-run if necessary, but it's only able to do this if the initial cmake run succeeded.

**Comment by tomjakubowski** [comment]
Rebasing is proving to be a pain. I'm happy to do it, but how did non-merge commits end up on master that aren't on dev? :[

**Comment by sandover** [comment]
Tom is super busy, any way you can take the baton @Gobiner ?

**Comment by jshrake** [comment]
Merged #114. Closing

**Pull request closed without merging**
