### PR TITLE
log commands to /tmp/obi.log on remotes

### PR DESCRIPTION
**Pull request by Gobiner**
In response to #67 

This doesn't log every piece of information imaginable but it is readable.

```
└[~]> ssh -t wh-wall-center tail -n 10 /tmp/obi.log
2017-01-30 20:42:42 UTC -ziuxhmgo- obi stop by arice: pkill -SIGTERM -f '[a-z/]+newsdisco .*' || true
2017-01-30 20:42:52 UTC -2weln7u5- obi stop by arice: pkill -SIGTERM -f '[a-z/]+newsdisco .*' || true
2017-01-30 20:43:43 UTC -o66xghvp- obi build by arice: mkdir -p /tmp/arice/newsdisco
2017-01-30 20:43:43 UTC -o66xghvp- obi build by arice: fabric rsync local=/Users/arice/newsdisco/ remote=/tmp/arice/newsdisco
2017-01-30 20:43:52 UTC -o66xghvp- obi build by arice: mkdir -p /tmp/arice/newsdisco/build
2017-01-30 20:43:52 UTC -o66xghvp- obi build by arice: cmake -H"/tmp/arice/newsdisco" -B"/tmp/arice/newsdisco/build" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1
2017-01-30 20:43:55 UTC -o66xghvp- obi build by arice: cmake --build "/tmp/arice/newsdisco/build" -- -j32 -l32
```

### CODE REVIEW

**Comment by sandover** [comment]
Would it make sense to print the command on a separate line?  Might make for easier post-processing -- or cut and pasting.  Then again it might make grepping less easy.  I dunno, just a thought, feel free to ignore.

**Comment by EchoAbstract** [comment]
@sandover, @Gobiner a blend of the two would be JSON, like:

```
{'date': '2017-01-30 20:42:52 UTC', 'whatever-this-thing-is': '-2weln7u5-', 'cmd':  'obi stop by arice: pkill -SIGTERM -f '[a-z/]+newsdisco .*' || true'}
```

as a single line it's still grepable, and you can easily use JSON tools (or treat it as slaw) to post-process.

**Comment by sandover** [comment]
You interest me, sir.  Please GOTO https://gitlab.oblong.com/solutions/tasks/issues/122

**Comment by tomjakubowski** [comment]
One weird trick to break obi for everyone: change your local username to [`obi.log`](http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap03.html#tag_03_426).

**Pull request closed without merging**
