### PR TITLE
add argument quoting to shell commands

### PR DESCRIPTION
**Pull request by Gobiner**
related to issue #51

### CODE REVIEW

**Comment by Gobiner** [comment]
This change has a meaningful compatibility problem: `build-args: ["-j32 -l32"]` will be treated as a single complex argument, being wrapped and turned into `cmake whatev '-j32 -l32' what ever`. The solution is to change every project.yaml in existence, separating the build-args list into two elements. I've made that project.yaml change to the obi templates (cpp gspeak greenhouse growroom seabed).

**Comment by tomjakubowski** [comment]
Good catch on the backwards compat issue. We probably have a handful of similar issues in various project.yaml files.

How does this change interact with the `debuggers` map?  We specify those as strings which get prepended to the launch-args with a space:

```
debuggers:
  gdb: "gdb -ex run --args"
  lldb: "lldb --"
  strace: "sudo strace"
  apitrace: "apitrace trace"
```

**Comment by tomjakubowski** [comment]
OK, I've convinced myself re: debuggers that there shouldn't be a problem. You're still welcome to find a problem I missed of course.

**Comment by jshrake** [comment]
> The solution is to change every project.yaml in existence, separating the build-args list into two elements. 

The resolution of #51 does not warrant changing every project.yaml in existence. Could we get a fix that's backwards compatible with the existing project.yaml files?

**Comment by Gobiner** [comment]
I could change it to not escape build arguments. I ran into compatibility problems escaping cmake-args, for example, so you'll see that they're not passed through the `shlexquote` function.

The way I see it, `build-args: ["-j8 -l8"]` is wrong and should be changed to `build-args: ["-j8", "-l8']`. I'm happy to make those fixes to project.yamls.

**Comment by tomjakubowski** [comment]
re: backwards compatibility, we could introduce a new key for build-args/whatever that does quoting properly, and obi could give some helpful spew in the case that the old key is detected in a project.yaml file. then, in a future major version of obi, we'd rip the band-aid, and accept either the old or new key but require quoting for both.

**Pull request merged**
