### PR TITLE
add a sentinel file to build dir to avoid re-running cmake

### PR DESCRIPTION
**Pull request by Gobiner**
This is my "rebased" version of PR #113.

### CODE REVIEW

**Comment by Gobiner** [comment]
In my testing thus far, this change seems to be working.

**Comment by jshrake** [comment]
lgtm

**Comment by tomjakubowski** [comment]
An interesting quirk of this MR is that you now have to `obi clean` or manually re-run cmake if you change the cmake-args.

We could consider storing the value of cmake-args in that hello-obi.txt file when it's creating, and comparing the current value with the value stored in the filesystem to determine whether to re-run cmake.

**Comment by tomjakubowski** [comment]
filed here #120

**Pull request merged**
