### PR TITLE
add SIGINT handler to prevent stack trace spew

### LINKED ISSUE #87: obi spews a stack trace when user presses ^C
Users pressing control-C to stop obi (and any underlying processes) is a use case we need to support. Right now, ^C stops obi but results in obi spewing a python stack trace. The stack trace isn't meaningful and should be suppressed.

### PR DESCRIPTION
**Pull request by Gobiner**
fixes #87

### CODE REVIEW

**Comment by sandover** [comment]
So this addresses #87 but not #66, is that right?

**Comment by tomjakubowski** [comment]
I think @dankegel should take a look at this. My only comment is that installing a global signal handler gives me the willies, especially in the presence of multiprocessing (thanks, fabric).

**Comment by sandover** [comment]
bumped @dankegel

**Comment by dankegel** [comment]
Seems plausible to me.  I trust fabric is used to this.

**Comment by sandover** [comment]
Meaning, you feel comfortable @dankegel ?

**Comment by Gobiner** [comment]
This approach does not play well with fabric's use of multiprocessing. Many processes are spawned and they each receive the interrupt and produce spew.

**Pull request closed without merging**
